# STAGE 1: Build
FROM node:14-bullseye as builder
RUN \
  apt-get update \
  && apt-get -y install gettext-base \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
ADD package.json ./package.json
ADD package-lock.json ./package-lock.json

RUN npm install --save-dev webpack
RUN npm ci

ADD . .

RUN envsubst < .env.example > .env

RUN npm run build:ssr

# STAGE 2: Run the server
FROM node:14-bullseye
RUN \
  apt-get update \
  && apt-get -y install gettext-base \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# From "builder" stage, copy over dist
WORKDIR /tmp

ADD package.json ./package.json
COPY --from=builder /tmp/dist /tmp/dist

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
