# STAGE 1: Build
FROM node:16-bullseye-slim
RUN \
  apt-get update \
  && apt-get -y install gettext-base \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ADD package.json ./package.json
ADD package-lock.json ./package-lock.json

ENV NODE_ENV=production
RUN npm install --save-dev webpack
RUN npm install -g @angular/cli
RUN npm ci

ADD . .

RUN envsubst < .env.example > .env

RUN npm run build:ssr

EXPOSE 4000

RUN chmod +x docker-entrypoint.sh

# ENTRYPOINT docker-entrypoint.sh
CMD ["./docker-entrypoint.sh"]
